### ISSUE TITLE
update readme to work with new repository

### ISSUE THREAD

**Issue by dschristianson** [BASIN-3D/basin3d#17] opened 2020-12-15 22:28 UTC
The readme references SFA-Watershed and basin3d-core. Change these references when ready to push to the new repo.

**Comment by heycatwonton** [comment] 2021-02-08 18:18
Duplicate of BASIN-3D/basin3d#28 and BASIN-3D/basin3d#27

**Closed by heycatwonton** 2021-02-08 18:18 UTC
