### ISSUE TITLE
requirements fail to install (following readme instructions)

### ISSUE THREAD

**Issue by dschristianson** [BASIN-3D/basin3d#18] opened 2020-12-15 22:35 UTC
The following occurred while walking thru README set up...

```
$ conda install $(cat requirements.txt) pytest
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - tinydb

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by dschristianson** [comment] 2020-12-15 22:39
Work around:
Installed pandas, pyyaml, and requests using `conda install <package>`
Installed tinydb using `pip install tinydb`

All tests passed.

**Comment by vchendrix** [comment] 2020-12-17 00:38
> Work around:
> 
> Installed pandas, pyyaml, and requests using `conda install <package>`
> 
> Installed tinydb using `pip install tinydb`
> 
> 
> 
> All tests passed.

Is this just a documentation issue?

**Comment by dschristianson** [comment] 2020-12-17 03:25
I think we can probably just change the documentation? 

I thought previously I had set up my local instance using the current instructions, but either I am mis-remembering or something has changed with tinydb not being available via conda. Not sure.

**Comment by vchendrix** [comment] 2020-12-17 18:53
We need to update the documentation to specifiy the following
```
conda install $(cat requirements.txt | grep -v tinydb) pytest
pip install pytest-flake8 pytest-mypy pytest-cov sphinx PSphinxTheme tinydb
python setup.py develop
```

We also need to update the following command to create a conda environment call basin3d and not basin3d-core.

```
conda create -y -n basin3d python=3.7
```

**Comment by vchendrix** [comment] 2021-01-29 17:31
Closing duplicate of BASIN-3D/basin3d#7

**Closed by vchendrix** 2021-01-29 17:31 UTC
Labels: duplicate
